DROP TABLE LOGINDETAILS;
DROP TABLE USERDETAILS;
DROP TABLE PULSERECORD;


CREATE TABLE LOGINDETAILS
       (USER_ID NUMBER(4)  PRIMARY KEY NOT NULL,
	   USERNAME VARCHAR2(20),
        PASSWORD VARCHAR2(10));
        
        
INSERT INTO LOGINDETAILS VALUES
        (1001, 'Deliwe',  'DDDD');
INSERT INTO LOGINDETAILS VALUES
        (1002, 'Botlhale',  'BBBB');
INSERT INTO LOGINDETAILS VALUES
        (1003, 'Tshiamo',   'TTTT');
INSERT INTO LOGINDETAILS VALUES
        (1004, 'Smanga',  'SSSS');
INSERT INTO LOGINDETAILS VALUES
        (1005, 'Fundiswa', 'FFFF');

CREATE TABLE USERDETAILS
       (
	   USER_ID NUMBER(4)  PRIMARY KEY NOT NULL,
       NAME VARCHAR2(14),
       SURNAME VARCHAR2(13),
       AGE NUMBER(2),	
	   GENDER CHAR(1));
       
INSERT INTO USERDETAILS VALUES (1001, 'Deliwe', 'Mahlase',23,'F');
INSERT INTO USERDETAILS VALUES (1002, 'Botlhale', 'Malora',21,'F');
INSERT INTO USERDETAILS VALUES (1003, 'Tshiamo',  'Matiza',22,'M');
INSERT INTO USERDETAILS VALUES (1004, 'Smanga', 'Zikalala',21,'M');
INSERT INTO USERDETAILS VALUES (1004, 'Fundiswa', 'Khanyi',21,'F');

CREATE TABLE PULSERECORD
        ( USER_ID NUMBER(4)  PRIMARY KEY NOT NULL,
          PURLSE_RATE NUMBER(7,2),
          MESSAGE VARCHAR2(30));


INSERT INTO PULSERECORD VALUES (1001,65,'Congradulations youbare in a good space');
INSERT INTO PULSERECORD VALUES (1002,150 , 'Your heart beat is high please calm down');
INSERT INTO PULSERECORD VALUES (1003,170, 'Please do not be sad evrything is gonna be okay');
INSERT INTO PULSERECORD VALUES (1004,100, 'Be patient');

commit;